name: Android Multi-ABI Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Setup Gradle (with caching)
      uses: gradle/actions/setup-gradle@v4

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    - name: Build APKs (all ABIs)
      run: |
        ./gradlew assembleDebug
        ./gradlew assembleRelease

    - name: Upload Debug APKs (all ABIs)
      uses: actions/upload-artifact@v4
      with:
        name: debug-apks
        path: app/build/outputs/apk/debug/*.apk

    - name: Upload Release APKs (all ABIs)
      uses: actions/upload-artifact@v4
      with:
        name: release-apks
        path: app/build/outputs/apk/release/*.apk
